server:
  address: localhost
  port: 8080

spring:
  application:
    name: AttestYoutube
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: ""
    driver-class-name: org.postgresql.Driver
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
